import type { AppDefinition } from '@/store/useStore';

export const apps: AppDefinition[] = [
  {
    id: 'file-manager',
    name: 'File Manager',
    icon: 'Folder',
    component: 'FileManager',
    defaultWidth: 800,
    defaultHeight: 600,
  },
  {
    id: 'text-editor',
    name: 'Text Editor',
    icon: 'FileText',
    component: 'TextEditor',
    defaultWidth: 700,
    defaultHeight: 500,
  },
  {
    id: 'code-editor',
    name: 'Code Editor',
    icon: 'Code2',
    component: 'CodeEditor',
    defaultWidth: 900,
    defaultHeight: 650,
  },
  {
    id: 'terminal',
    name: 'Terminal',
    icon: 'Terminal',
    component: 'TerminalApp',
    defaultWidth: 700,
    defaultHeight: 450,
  },
  {
    id: 'calculator',
    name: 'Calculator',
    icon: 'Calculator',
    component: 'Calculator',
    defaultWidth: 320,
    defaultHeight: 480,
  },
  {
    id: 'paint',
    name: 'Paint',
    icon: 'Paintbrush',
    component: 'Paint',
    defaultWidth: 800,
    defaultHeight: 600,
  },
  {
    id: 'snake',
    name: 'Snake Game',
    icon: 'Gamepad2',
    component: 'SnakeGame',
    defaultWidth: 500,
    defaultHeight: 550,
  },
  {
    id: 'minesweeper',
    name: 'Minesweeper',
    icon: 'Bomb',
    component: 'Minesweeper',
    defaultWidth: 500,
    defaultHeight: 600,
  },
  {
    id: 'chess',
    name: 'Chess',
    icon: 'Castle',
    component: 'ChessGame',
    defaultWidth: 600,
    defaultHeight: 650,
  },
  {
    id: 'music-player',
    name: 'Music Player',
    icon: 'Music',
    component: 'MusicPlayer',
    defaultWidth: 600,
    defaultHeight: 500,
  },
  {
    id: 'photo-gallery',
    name: 'Photo Gallery',
    icon: 'Image',
    component: 'PhotoGallery',
    defaultWidth: 800,
    defaultHeight: 600,
  },
  {
    id: 'calendar',
    name: 'Calendar',
    icon: 'Calendar',
    component: 'CalendarApp',
    defaultWidth: 700,
    defaultHeight: 600,
  },
  {
    id: 'weather',
    name: 'Weather',
    icon: 'Cloud',
    component: 'Weather',
    defaultWidth: 500,
    defaultHeight: 600,
  },
  {
    id: 'maps',
    name: 'Maps',
    icon: 'Map',
    component: 'Maps',
    defaultWidth: 800,
    defaultHeight: 600,
  },
  {
    id: 'clock',
    name: 'Clock',
    icon: 'Clock',
    component: 'ClockApp',
    defaultWidth: 500,
    defaultHeight: 450,
  },
  {
    id: 'task-manager',
    name: 'Task Manager',
    icon: 'Activity',
    component: 'TaskManager',
    defaultWidth: 700,
    defaultHeight: 500,
  },
  {
    id: 'notepad',
    name: 'Notepad',
    icon: 'StickyNote',
    component: 'Notepad',
    defaultWidth: 600,
    defaultHeight: 450,
  },
  {
    id: 'camera',
    name: 'Camera',
    icon: 'Camera',
    component: 'CameraApp',
    defaultWidth: 700,
    defaultHeight: 550,
  },
  {
    id: 'browser',
    name: 'Web Browser',
    icon: 'Globe',
    component: 'Browser',
    defaultWidth: 900,
    defaultHeight: 650,
  },
  {
    id: 'settings',
    name: 'Settings',
    icon: 'Settings',
    component: 'SettingsApp',
    defaultWidth: 700,
    defaultHeight: 550,
  },
  {
    id: 'email',
    name: 'Email',
    icon: 'Mail',
    component: 'EmailClient',
    defaultWidth: 900,
    defaultHeight: 600,
  },
  {
    id: 'video',
    name: 'Video Player',
    icon: 'Film',
    component: 'VideoPlayer',
    defaultWidth: 800,
    defaultHeight: 600,
  },
];

export const getAppById = (id: string) => apps.find((app) => app.id === id);
